{{- if .Values.istio.enabled -}}
{{- if .Values.istio.gateway.create -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "davhttpd.fullname" . }}
  labels:
    {{- include "davhttpd.labels" . | nindent 4 }}  
spec:
  selector:
    {{ toYaml .Values.istio.gateway.selector }}
  servers:
  - hosts:
    {{- range .Values.istio.hosts }}
    - {{ .host }}
    {{- end }}
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    {{- range .Values.istio.hosts }}
    - {{ .host }}
    {{- end }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ include "davhttpd.fullname" . }}
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
---
{{- end }}
{{- end }}