{{- if .Values.istio.enabled -}}
{{- $fullName := include "davhttpd.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "davhttpd.fullname" . }}
  labels:
    {{- include "davhttpd.labels" . | nindent 4 }}  
spec:
  hosts:
  {{- range .Values.istio.hosts }}
  - {{ .host }}
  {{- end }}
  gateways:
  {{- if .Values.istio.gateway.create }}
  - {{ include "davhttpd.fullname" . }}
  {{- else -}}
  - {{ .Values.istio.gateway.name }}
  {{- end }}
  http:
  - route:
    - destination:
        host: {{ $fullName }}
        port:
          number: {{ $svcPort }}   
{{- end }}