name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '*'
      - 'release/*'
    tags:
      - 'v*'
  pull_request:

env:
  DOCKERHUB_SLUG: peterfromthehill/davhttpd

jobs:
  build:
    permissions:
      contents: write # to create GitHub release (softprops/action-gh-release)

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.DOCKERHUB_SLUG }}
          ### versioning strategy
          ### push semver tag v3.2.1 on main (default branch)
          # peterfromthehill/davhttpd:3.2.1
          # peterfromthehill/davhttpd:3.2
          # peterfromthehill/davhttpd:3
          # peterfromthehill/davhttpd:latest
          ### push semver prelease tag v3.0.0-beta.1 on main (default branch)
          # peterfromthehill/davhttpd:3.0.0-beta.1
          ### push on main
          # peterfromthehill/davhttpd:edge
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr
            type=edge
          labels: |
            org.opencontainers.image.title=davhttpd
            org.opencontainers.image.description=The proxy for webdav managed sites
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build image
        uses: docker/bake-action@v4
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: image-all
          push: true #${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}